
var activities = [
    {id:"01", title:"Nottingham University", place:"Nottingham", geo:[[52.95,-1.133]], start_time:"1973", end_time:"1976", pic:"../static/images/nottingham.jpg", 
    desc:'<p>B.Sc. Mathematics, University of Nottingham</p> '},    
    {id:"02", title:"Benton & Bowles", place:"London", geo:[[51.501,-0.126]], start_time:"1977", end_time:"1979", logo:"../static/images/logos/publicis_logo.jpg", pic:"../static/images/publicis.jpg", 
    desc:'<p>(now Publicis), London advertising agency for Moet Chandon, Dewars, Kraft Foods, etc.</p><p>My first job was advertising buyer, then computer operations.</p>'},
    {id:"03", title:"BAe Systems", place:"London", geo:[[51.372,-0.453]], start_time:"1979", end_time:"1981", pic:"../static/images/tornado.jpg", logo:"../static/images/logos/bae_logo.jpg", 
    desc:'<p>For British Aerospace, developed systems on IBM mainframes to control production of combat (Tornado, Harrier) and civilian (Concorde, Airbus) aircraft. </p>'},
    {id:"04", title:"AGS", place:"NYC", geo:[[40.714,-73.961]], start_time:"1984", end_time:"1988", logo:"../static/images/logos/verizon_logo.jpg", pic:"../static/images/prices.jpg", 
    desc:'<p>Led AGS teams developing software including FX trading for BoA/Merrill Lynch, price reporting for CME Group, international funds transfer for JP Morgan Chase, computer leasing for IBM, ATMs for RBS NatWest.</p>'}, 
    {id:"05", title:"NYC DoE", place:"NYC", geo:[[40.693,-73.990]], start_time:"1981", end_time:"1984", pic:"../static/images/NY_boroughs.jpg", logo:"../static/images/logos/doe_logo.jpg", 
    desc:'<p>Analyst/programmer using IBM mainframe (MVS, CICS) for payroll and HR programs for the NYC Department of Education</p>'},    
    {id:"06", title:"IBM Credit", place:"Stamford", geo:[[41.097,-73.552]], start_time:"1984", end_time:"1985", logo:"../static/images/logos/ibm_logo.jpg", 
    desc:'<p>Developed reporting and analytics systems for IBM Credit Corporation in Stamford</p>'},
    {id:"07", title:"Merrill Lynch", geo:[[40.714,-73.961]], start_time:"1985", end_time:"1987", pic:"../static/images/ml.jpg", logo:"../static/images/logos/ml_logo.jpg", 
    desc:'<p>Risk management system for Merrill Lynch.</p>'},
    {id:"08", title:"NatWest USA", geo:[[40.818205, -73.206878]], start_time:"1984", end_time:"1984", pic:"../static/images/natwest.jpg", logo:"../static/images/logos/natwest_logo.jpg", 
    desc:'<p>ATM support for NatWest USA in Long Island</p>'},
    {id:"10", title:"LSE", place:"London", geo:[[51.51411, -0.11664]], start_time:"2010", end_time:"2013", logo:"../static/images/logos/lse_logo.jpg", 
    desc:'<p>B.Sc. Information Systems & Management, University of London (LSE)</p>'},
    {id:"11", title:"IBM AIX", place:"Raleigh", geo:[[19.433,-99.133],[32.776,-96.797],[35.819,-78.645],[43.703,7.266],[40.428,-3.702]], start_time:"1990", end_time:"1994", pic:"../static/images/rs6000.jpg", logo:"../static/images/logos/ibm_logo.jpg", 
    desc:'<p>Founded and ran a business in Raleigh, specializing in AIX (IBM UNIX).</p><p>Trained IBM engineers in AIX in Dallas, Mexico, Nice, Madrid, and other locations</p>'}, 
    {id:"12", title:"Kaplan Australia", place:"Sydney", geo:[[-33.86,151.211]], start_time:"2011", end_time:"2011", pic:"../static/images/adeladesce.jpg", logo:"../static/images/logos/kaplan.jpg", 
    desc:'<p>Reviewing and supporting several Kaplan efforts in online learning in Sydney</p>'},
    {id:"13", title:"Outsourcing", place:"Delhi", geo:[[28.61,77.23]], start_time:"2010", end_time:"2010", pic:"../static/images/delhi.jpg", logo:"../static/images/logos/kaplan.jpg", 
    desc:'<p>Worked with Kaplan in-house offshore software development center on various projects in New Delhi</p>'},
    {id:"14", title:"Research conference", place:"Crete", geo:[[35.21,24.91]], start_time:"2011", end_time:"2011", pic:"../static/images/crete.jpg", logo:"../static/images/logos/moodle.jpg", 
    desc:'<p>Attended Moodle research conference on e-learning in Crete</p>'},  
    {id:"15", title:"Adelaide", place:"Adelaide", geo:[[-34.929,138.601]], start_time:"2010", end_time:"2011", logo:"../static/images/logos/adelaide_logo.jpg", pic:"../static/images/adelaideu.jpg", 
    desc:'<p>Partnered with the University of Adelaide on online masters programs in Business, Project Management, and Innovation and Entrepreneurship.</p>'},          
    {id:"16", title:"Microsoft", place:"Chicago", geo:[[41.882,-87.628]], start_time:"1994", end_time:"1996", pic:"../static/images/burger.jpg", logo:"../static/images/logos/ms_logo.jpg", 
    desc:'<p>In Chicago, managed a team supporting software and infrastructure engagements for United Airlines, Kraft Foods and McDonalds.</p>'},   
    {id:"17", title:"United Airlines", geo:[[41.882,-87.628]], start_time:"1994", end_time:"1996", pic:"../static/images/united.jpg", logo:"../static/images/logos/united_logo.jpg", 
    desc:'<p>Internet reservation system for United Airlines</p>'},
    {id:"18", title:"AGS", place:"Mountainside", geo:[[40.681,-74.36]], start_time:"1993", end_time:"1994", pic:"../static/images/roche.jpg", logo:"../static/images/logos/verizon_logo.jpg", 
    desc:'<p>For AGS (then a Verizon company, now NTT Data), ran a division consulting on strategy, algorithms, and analytics for companies including IBM, Verizon, and Hoffmann-La Roche.</p>'},
    {id:"19", title:"De Paul", place:"Chicago", geo:[[41.882,-87.628]], start_time:"1995", end_time:"1997", logo:"../static/images/logos/depaul_logo.jpg", 
    desc:'<p>De Paul University continuing education:</p><p>Managing enterprise software development using practical project examples.</p>'},
    {id:"21", title:"Microsoft", place:"Tampa", geo:[[27.91,-82.465]], start_time:"1996", end_time:"1998", pic:"../static/images/publix.jpg", logo:"../static/images/logos/ms_logo.jpg",  
    desc:'<p>As Managing Consultant in Florida, developed a consulting business serving enterprise customers with software development and operations/infrastructure services.</p>' +
    '<p>Customers included American Express, Burger King, Office Depot, Royal Caribbean, Carnival, Auto Nation, CSX, Harris, state agencies, and dot-coms.</p>' +
    '<p>Microsoft Consulting in Florida grew from two employees to forty, and major enterprise sales were made in several accounts.</p>'}, 
    {id:"22", title:"Darden", geo:[[41.882,-87.628]], start_time:"1997", end_time:"1997", pic:"../static/images/logos/darden_logos.jpg", 
    desc:'<p>Installed SQL Server as the store server in all Darden restaurants including Red Lobster, Olive Garden, and Bahama Breeze</p>'},         
    {id:"23", title:"Microsoft", place:"Atlanta", geo:[[33.755,-84.39]], start_time:"1999", end_time:"2000", logo:"../static/images/logos/ms_logo.jpg", 
    desc:'<p>Sold through MSDN events for developers, relationships with software vendors and integrators, and line-of-business sales. Successes included large SQL Server adoptions at Darden (Red Lobster/Olive Garden), Publix, and agencies of the State of Flordesca. </p>'},
    {id:"24", title:"Office Depot", geo:[[26.459,-80.083]], start_time:"2000", end_time:"2002", pic:"../static/images/od.jpg", logo:"../static/images/logos/officedepot.jpg", 
    desc:'<p>Internal portal for Office Depot, summarizing key sales data and plans. Used for daily huddle at 1000 retail stores.</p>'},     
    {id:"25", title:"Retail consulting", place:"Miami", geo:[[25.787,-80.224]], start_time:"2002", end_time:"2004", pic:"../static/images/elemis.jpg", logo:"../static/images/logos/elemis.jpg", 
    desc:'<p>Worked with Miami consulting firm on a distributed inventory system for spas on cruise lines, and a system for consignment sales of perfume at retail sites.</p>'}, 
    {id:"26", title:"Med cruising", place:"Istanbul", geo:[[41.014,28.955],[36.80,10.183]], start_time:"2003", end_time:"2003", pic:"../static/images/istanbul.jpg", 
    desc:'<p>Mediterranean -- Istanbul mosques, palaces, and the Grand Bazaar. </p><p>Mediterranean: Tunis, Rhodes, Santorini, Marseilles, Pompeii, Barcelona, Majorca, Naples</p>'},       
    {id:"28", title:"Kaplan", place:"Fort Lauderdale", geo:[[26.136,-80.142]], start_time:"2004", end_time:"2008", logo:"../static/images/logos/ku_logo.jpg", 
    desc:'<p>Ran the KU student team of twenty US developers plus similar-sized groups of outsourced resources in India and Mexico.</p>' +
    '<p>Managed admissions, academic advising, and financial adesc systems, and launched a lead generation entity which is now part of Education Dynamics.</p>' +
    '<p>Leader of Kaplan migration from VB and traditional processes to C# and Scrum-based development.</p>' +
    '<p>Managed Kaplan selection of Pearson/eCollege as their learning management system, and created a team to integrate it.</p>' +
    '<p>Led development of a Flash-based synchronous seminar for the Concord law school, now used across KU, and managed development of call center systems using Genesys software.</p>'},
    {id:"29", title:"Peru", place:"Lima", geo:[[-12.043,-77.028]], start_time:"2007", end_time:"2007", pic:"../static/images/mapi.jpg", 
    desc:'<p>Lima, Cuzco, and Macchu Pichu with the kids: llamas and ruins</p>'},    
    {id:"30", title:"Colloquy", place:"Delray Beach", geo:[[26.459,-80.083]], start_time:"2009", end_time:"2012", logo:"../static/images/logos/colloquy.jpg", pic:"../static/images/colloquy.jpg", 
    desc:'<p>CTO for this Kaplan startup, offering online admissions and education services in support of partner universities and Kaplan colleges in Asia/Pacific.</p>' +
    '<p>Clients include George Washington University, UT Austin, University College Dublin, and the University of Adelaide.' +
    '<p>Created new team and systems running on Amazon AWS in Europe, Asia/Pacific and the US. Won a company innovation award for use of open source and cloud computing and served on the CIO Council. Amazon, Moodle, Salesforce.com, and Alfresco became corporate global standards.</p>'}, 
    {id:"31", title:"Kaplan Hong Kong", place:"Hong Kong", geo:[[22.278,114.159],[1.300,103.80]], start_time:"2010", end_time:"2011", pic:"../static/images/hongkong.jpg", logo:"../static/images/logos/kaplan.jpg", 
    desc:'<p>Installed Colloquy online education software in support of Kaplan colleges in Hong Kong and Singapore</p>'},    
    {id:"32", title:"Diving", place:"Brisbane", geo:[[-27.468,153.028]], start_time:"2010", end_time:"2010", pic:"../static/images/scuba.jpg", 
    desc:'<p>Scuba diving at Lady Elliott Island, Great Barrier Reef, near Brisbane</p>'},       
    {id:"33", title:"Noodle", place:"NYC", geo:[[40.714,-73.961]], start_time:"2012", end_time:"2014", logo:"../static/images/logos/noodle_logo.jpg", 
    desc:'<p>CTO of Noodle, an education search and recommendation web startup launched by the founder of The Princeton Review and 2U.</p>' +
     '<p>Replaced outsourced development with a NY-based team and developed a new IT architecture emphasizing Python, MongoDB, Solr, and a REST API.</p>' +
     '<p>Managing data acquisition, software development, and IT operations using Amazon cloud services.</p>'},
    {id:"34", title:"Thinkful", place:"NYC", geo:[[40.714,-73.961]], start_time:"2013", end_time:"2013", logo:"../static/images/logos/thinkful.jpg", 
    desc:'<p>Certificate in front-end development using HTML, CSS, JavaScript, and JQuery.</p>'},       
    {id:"35", title:"Bank of America", place:"Charlotte", geo:[[35.22734, -80.84302]], start_time:"2014", end_time:"2014", pic:"../static/images/boa.jpg", logo:"../static/images/logos/boa_logo.jpg", 
    desc:'<p>Helping to scale up Global Crimes Technology solutions using Java with Spring and Oracle, and introducing MongoDB.</p>'}, 
    {id:"36", title:"NextEra Energy", place:"Jupiter", geo:[[26.90485, -80.30062]], start_time:"2014", end_time:"2015", pic:"../static/images/nextera.jpg", logo:"../static/images/logos/nextera_logo.jpg", 
    desc:'<p>Developing analytical applications for smart meters, streetlights, and asset/fault reporting using C#, Java, and Groovy with MongoDB and GreenPlum.</p>'}        
];
